// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfReactorUI.ScaffoldApp
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TypeSourceGenerator : TypeSourceGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// ------------------------------------------------------------------------------" +
                    "\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//     Avaloni" +
                    "aReactorUI.ScaffoldApp Version: ");
            
            #line 10 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Assembly.GetExecutingAssembly().GetName().Version));
            
            #line default
            #line hidden
            this.Write(@"
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections;
using System.IO;
using System.Reflection;

using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Windows.Media.Imaging;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Controls.Primitives;
using System.Windows.Navigation;

using WpfReactorUI.Internals;
");
            
            #line 36 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var usingNS in AdditionalUsings) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 37 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(usingNS));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 38 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 40 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial interface IRx");
            
            #line 42 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 42 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n    ");
            
            #line 44 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        PropertyValue<");
            
            #line 45 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">? ");
            
            #line 45 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n    ");
            
            #line 46 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 48 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        Action? ");
            
            #line 49 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action { get; set; }\r\n        Action<object?, ");
            
            #line 50 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetMethod("Invoke").GetParameters()[1].ParameterType.Name));
            
            #line default
            #line hidden
            this.Write(">? ");
            
            #line 50 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs { get; set; }\r\n    ");
            
            #line 51 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n    ");
            
            #line 53 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (!IsSealed) { 
            
            #line default
            #line hidden
            this.Write("    public partial class Rx");
            
            #line 54 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("<T> : ");
            
            #line 54 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write("<T>, IRx");
            
            #line 54 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" where T : ");
            
            #line 54 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(", new()\r\n    ");
            
            #line 55 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("    public partial class Rx");
            
            #line 56 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 56 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 56 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(">, IRx");
            
            #line 56 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 57 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    {\r\n        public Rx");
            
            #line 59 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        { \r\n        \r\n        }\r\n\r\n        ");
            
            #line 64 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (!IsSealed) { 
            
            #line default
            #line hidden
            this.Write("        public Rx");
            
            #line 65 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("(Action<T?> componentRefAction)\r\n        ");
            
            #line 66 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public Rx");
            
            #line 67 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("(Action<");
            
            #line 67 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("?> componentRefAction)\r\n        ");
            
            #line 68 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            : base(componentRefAction)\r\n        {\r\n\r\n        }\r\n\r\n        ");
            
            #line 74 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        PropertyValue<");
            
            #line 75 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">? IRx");
            
            #line 75 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 75 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n        ");
            
            #line 76 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 78 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        Action? IRx");
            
            #line 79 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 79 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action { get; set; }\r\n        Action<object?, ");
            
            #line 80 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetMethod("Invoke").GetParameters()[1].ParameterType.Name));
            
            #line default
            #line hidden
            this.Write(">? IRx");
            
            #line 80 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 80 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs { get; set; }\r\n        ");
            
            #line 81 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        protected override void OnUpdate()\r\n        {\r\n            OnBeginUpdat" +
                    "e();\r\n\r\n            ");
            
            #line 87 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (Properties.Any()) { 
            
            #line default
            #line hidden
            this.Write("            var thisAsIRx");
            
            #line 88 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 88 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            ");
            
            #line 89 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("            SetPropertyValue(NativeControl, ");
            
            #line 90 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 90 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Property, thisAsIRx");
            
            #line 90 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 90 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 91 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 92 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
            base.OnUpdate();

            OnEndUpdate();
        }

        partial void OnBeginUpdate();
        partial void OnEndUpdate();
        partial void OnAttachingNewEvents();
        partial void OnDetachingNewEvents();

        protected override void OnAttachNativeEvents()
        {
            OnAttachingNewEvents();

            ");
            
            #line 108 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (Events.Any()) { 
            
            #line default
            #line hidden
            this.Write("            var thisAsIRx");
            
            #line 109 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 109 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            ");
            
            #line 110 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("            if (thisAsIRx");
            
            #line 111 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 111 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action != null || thisAsIRx");
            
            #line 111 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 111 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs != null)\r\n            {\r\n                NativeControl.");
            
            #line 113 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(" += NativeControl_");
            
            #line 113 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            ");
            
            #line 115 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 116 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            base.OnAttachNativeEvents();\r\n        }\r\n\r\n        ");
            
            #line 121 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        private void NativeControl_");
            
            #line 122 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("(object? sender, ");
            
            #line 122 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetMethod("Invoke").GetParameters()[1].ParameterType.Name));
            
            #line default
            #line hidden
            this.Write(" e)\r\n        {\r\n            var thisAsIRx");
            
            #line 124 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" = (IRx");
            
            #line 124 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            thisAsIRx");
            
            #line 125 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 125 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action?.Invoke();\r\n            thisAsIRx");
            
            #line 126 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 126 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs?.Invoke(sender, e);\r\n        }\r\n        ");
            
            #line 128 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        protected override void OnDetachNativeEvents()\r\n        {\r\n            " +
                    "OnDetachingNewEvents();\r\n\r\n            ");
            
            #line 134 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (Events.Any()) { 
            
            #line default
            #line hidden
            this.Write("            if (NativeControl != null)\r\n            {\r\n            ");
            
            #line 137 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("            NativeControl.");
            
            #line 138 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(" -= NativeControl_");
            
            #line 138 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            ");
            
            #line 139 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n            ");
            
            #line 141 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            base.OnDetachNativeEvents();\r\n        }\r\n\r\n    }\r\n    ");
            
            #line 147 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (IsTypeNotAbstractWithEmptyConstructor) { 
            
            #line default
            #line hidden
            this.Write("    public partial class Rx");
            
            #line 148 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(" : Rx");
            
            #line 148 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 148 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public Rx");
            
            #line 150 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        { \r\n        \r\n        }\r\n\r\n        public Rx");
            
            #line 155 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("(Action<");
            
            #line 155 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("?> componentRefAction)\r\n            : base(componentRefAction)\r\n        {\r\n\r\n    " +
                    "    }\r\n    }\r\n    ");
            
            #line 161 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    public static partial class Rx");
            
            #line 162 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n    {\r\n        ");
            
            #line 164 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var property in Properties) { 
            
            #line default
            #line hidden
            this.Write("        public static T ");
            
            #line 165 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 165 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 165 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 165 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write(") where T : IRx");
            
            #line 165 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 167 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 167 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 167 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 167 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return ");
            
            #line 168 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 170 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 170 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Func<");
            
            #line 170 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 170 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write("Func) where T : IRx");
            
            #line 170 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 172 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 172 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 172 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 172 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.CamelCase()));
            
            #line default
            #line hidden
            this.Write("Func);\r\n            return ");
            
            #line 173 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 175 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (property.PropertyType.Name == "Thickness") { 
            
            #line default
            #line hidden
            this.Write("        public static T ");
            
            #line 176 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 176 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", double leftRight, double topBottom) where T : IRx");
            
            #line 176 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 178 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 178 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 178 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new Thickness(leftRight, topBottom, leftRight, topBottom));\r\n            return" +
                    " ");
            
            #line 179 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 181 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 181 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", double uniformSize) where T : IRx");
            
            #line 181 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 183 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 183 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 183 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new Thickness(uniformSize));\r\n            return ");
            
            #line 184 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 186 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 187 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (IsCommand(property.PropertyType)) { 
            
            #line default
            #line hidden
            this.Write("        public static T ");
            
            #line 188 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 188 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Action action) where T : IRx");
            
            #line 188 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 190 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 190 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 190 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new ActionCommand(action));\r\n            return ");
            
            #line 191 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 193 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 194 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 if (property.PropertyType.Name == "ImageSource") { 
            var propertyName = property.Name.Length <= 6 ? property.Name : property.Name.Substring(0, property.Name.Length - 6); 
            
            #line default
            #line hidden
            this.Write("\r\n        public static T ");
            
            #line 197 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 197 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", string file) where T : IRx");
            
            #line 197 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 199 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 199 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 199 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new BitmapImage(new Uri(file)));\r\n            return ");
            
            #line 200 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        /*\r\n        public static T ");
            
            #line 203 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 203 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", string resourceName, Assembly sourceAssembly) where T : IRx");
            
            #line 203 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 205 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 205 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 205 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromResource(resourceName, sourceAssembly));\r\n            return ");
            
            #line 206 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        */\r\n        public static T ");
            
            #line 209 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 209 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Uri imageUri) where T : IRx");
            
            #line 209 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 211 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 211 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 211 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new BitmapImage(imageUri));\r\n            return ");
            
            #line 212 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        /*\r\n        public static T ");
            
            #line 215 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 215 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Uri imageUri, bool cachingEnabled, TimeSpan cacheValidity) where T : IRx");
            
            #line 215 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 217 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 217 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 217 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(new UriImageSource\r\n            {\r\n                Uri = imageUri,\r\n           " +
                    "     CachingEnabled = cachingEnabled,\r\n                CacheValidity = cacheVali" +
                    "dity\r\n            });\r\n            return ");
            
            #line 223 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        public static T ");
            
            #line 225 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 225 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Func<Stream> imageStream) where T : IRx");
            
            #line 225 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 227 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 227 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new PropertyValue<");
            
            #line 227 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.ToResevedWordTypeName()));
            
            #line default
            #line hidden
            this.Write(">(ImageSource.FromStream(imageStream));\r\n            return ");
            
            #line 228 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        */\r\n            ");
            
            #line 231 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 232 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 233 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 foreach (var ev in Events) { 
            
            #line default
            #line hidden
            this.Write("        public static T On");
            
            #line 234 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 234 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Action ");
            
            #line 234 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("Action) where T : IRx");
            
            #line 234 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 236 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 236 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("Action = ");
            
            #line 236 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("Action;\r\n            return ");
            
            #line 237 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        public static T On");
            
            #line 240 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("<T>(this T ");
            
            #line 240 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(", Action<object?, ");
            
            #line 240 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.EventHandlerType.GetMethod("Invoke").GetParameters()[1].ParameterType.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 240 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs) where T : IRx");
            
            #line 240 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 242 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 242 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs = ");
            
            #line 242 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("ActionWithArgs;\r\n            return ");
            
            #line 243 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        ");
            
            #line 245 "C:\Users\ado\source\repos\github\reactorui-wpf\src\WpfReactorUI.ScaffoldApp\TypeSourceGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TypeSourceGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
